### ISSUE TITLE
sphinx: Build error after pydata-sphinx-theme 0.9.0

### ISSUE THREAD

**Issue by ventureoo** [ventureoo/ARU#79]
~~May be related with: https://github.com/pydata/pydata-sphinx-theme/issues/710~~
```
Extension error (pydata_sphinx_theme):
Handler <function _overwrite_pygments_css at 0x7fc4821fe4c0> for event 'build-finished' threw an exception (exception: 'HtmlFormatter' object has no attribute 'get_linenos_style_defs')
Traceback (most recent call last):
  File "/entrypoint.py", line 22, in <module>
    action.build_all_docs(github_env, [os.environ.get("INPUT_DOCS-FOLDER")])
  File "/sphinx_action/action.py", line 167, in build_all_docs
    raise RuntimeError("Build failed")
```

A temporary workaround: https://github.com/ventureoo/ARU/commit/afe292d7eb4056b6e05dc549258bdf298964b445

**Comment by ventureoo** [comment]
@ventureoo кстати я вот грешу на это новое обновление, а ARU с ним может тёмная тема появится в веб версии

**Comment by ventureoo** [comment]
Not related to upstream, should be fixed with https://github.com/ventureoo/ARU/pull/80
